config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :transactions

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many(
    :transactions,
    dependent: :destroy
  )

  has_attached_file(
    :avatar,
    styles:{ medium: "300x300>", thumb: "100x100>" },
    default_url: "/images/:style/missing.png"
  )
  validates_attachment_content_type(
    :avatar,
    content_type: /\Aimage\/.*\z/
  )
  validates(
    :firstname,
    presence: true,
    length: {
      maximum: 100
    }
  )
  validates(
    :lastname,
    presence: true,
    length: {
      maximum: 100
    }
  )
  validates(
    :email,
    format: {
      with: /\A([^@\s]+)@(softices\.com)\Z/i
    },
    uniqueness: true
  )
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:firstname, :lastname, :email, :password, :password_confirmation, :remember_me)}
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password, :remember_me)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:firstname, :lastname, :email, :password, :current_password, :avatar, :remember_me)}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :authenticate_user!
  def index
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_transactions, only: %i[show edit update destroy]
  def index
    @transactions = Transaction.all
  end

  def show; end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction= Transaction.new(transaction_params)
    @transaction.user_id = current_user.id
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transactions_path }
        format.json { render :index, status: :created }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def update
    respond_to do |format|
      if @transaction.update_attributes(transaction_params)
        format.html { redirect_to transactions_path, notice: "updated successfully" }
        format.json { render :show, status: :ok }
      else
        format.html { render :edit, notice: "Something went wrong"}
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_transactions
    @transaction = Transaction.find_by_id(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:user_id, :trans_type, :trans_amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/home/index.html.erb
<ul class="breadcrumb">
  <li>
    <a href="#">
      <span class="fa fa-home fa-fw"></span>
    </a>
  </li>
</ul>
<div class="panel-body" id="main">
  <div class="row main">
    <div class="col-lg-12">
      <h2 class="page-header">Dashboard</h2>
    </div>
  </div>
  <div class="col-lg-offset-1 col-lg-2 text-center">
    <div class="panel panel-warning">
      <div class="panel-body">
        <i class="fa fa-inr fa-5x" aria-hidden="true"></i>
      </div>
      <div class="panel-footer"><a href="<%= transactions_path%>"><span>Transactions</span></a></div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container text-center">
  <div class="row">
    <footer>
      <p>&copy; Company 2017</p>
    </footer>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="navbar-brand"><%= link_to "Authentication", root_path %></div>
  <div class="container">
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Transaction", transactions_path  %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right collapse navbar-collapse">
        <% if !current_user.blank? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Settings
            <span class="hidden-xs"> </span>
            <span class="visible-lg-inline">&nbsp;&nbsp;&nbsp;</span>
            <span class="fa fa-caret-down fa-fw"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="<%= edit_user_registration_path %>"> <span class="fa fa-user fa-fw"> </span>Edit</a></li>
            <div class="nav-divider"></div>
            <li><a href="<%= destroy_user_session_path %>" data-method: "delete" > <span class="fa fa-power-off fa-fw"> </span>Log Out</a></li>
          </ul>
        </li>
        <%end%>
      </ul>
    </div>
  </div>

app/views/layouts/_sidebar.html.erb
<div class="row">
  <div class="col-lg-3">
    <div class="well sidebar-nav">
      <h3>Sidebar</h3>
      <ul class="nav nav-list">
        <li class="nav-header">User</li>
        <li><%= link_to "Link1", "/path1"  %></li>
        <li><%= link_to "Link2", "/path2"  %></li>
        <li><%= link_to "Link3", "/path3"  %></li>
      </ul>
    </div><!--/.well -->
  </div><!--/span-->
  <div class="col-lg-9">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Authentication" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

  </head>
  <body>

    <% if !current_user.blank? %>
      <%= render 'layouts/header' %>
      <% render 'layouts/sidebar' %>
    <%end%>
    <%= bootstrap_flash %>
    <%= yield %>
    <% if !current_user.blank? %>
      <%= render 'layouts/footer' %>
    <%end%>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_for(@transaction, html: {class: "form-horizontal"}) do |f| %>
  <div class="container-fluid">
    <!-- <div class="row main col-lg-12"> -->
    <h3 class="page-header">Transaction Form</h3>
    <div class="form-group">
      <label class="col-sm-3 control-label">
        <%= f.label :trans_amount %>
      </label>
      <div class="col-sm-3">
        <%= f.text_field :trans_amount, class: "form-control", required: :required, placeholder: "Transaction Amount" %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-3 control-label">
        <%= f.label :trans_type %>
      </label>
      <div class="col-sm-3">
        <%= f.text_field :trans_type, class: "form-control", required: :required, placeholder: "Transaction type" %>
      </div>
    </div>
    <div class="col-lg-12">
      <div class="form-group">
        <%= f.submit class: "btn btn-primary col-xs-offset-3" %>
        <%= link_to "Back", transactions_path, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
<%end%>

app/views/transactions/edit.html.erb
<ul class="breadcrumb">
  <li><a href="<%= root_path %>"><span class="fa fa-home fa-fw"></span></a></li>
  <li><a href="<%= transactions_path %>">Transaction</a></li>
  <li><a href="<%= edit_transaction_path %>">New Transaction</a></li>
  <li class="active"><strong>Edit</strong></li>
</ul>
<%= render 'form' %>

app/views/transactions/index.html.erb
<ul class="breadcrumb">
  <li><a href="<%= root_path %>"><span class="fa fa-home fa-fw"></span></a></li>
  <li><%= link_to "Transactions", transactions_path %></li>
</ul>
<div class="container-fluid">
  <button class= "btn btn-default pull-right"><%= link_to "New", new_transaction_path %></button>
  <div class="row top15">
    <div class="col-sm-12">
      <div class="table-responsive">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>User</th>
              <th>Type</th>
              <th>Amount</th>
              <th>Date</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @transactions.each do |t| %>
              <tr>
                <td><%= t.try(:user).try(:firstname) %></td>
                <td><%= t.trans_type %></td>
                <td><%= t.trans_amount %></td>
                <td><%= t.created_at %></td>
                <td class="vert-aling">
                <%= link_to transaction_path(t),class: "btn btn-info btn-xs" do %><i class="fa fa-eye fa-fw"></i>&nbsp;View<% end%>
                <%= link_to edit_transaction_path(t),class: "btn btn-warning btn-xs" do %><i class="fa fa-pencil fa-fw"></i>&nbsp;Edit<% end%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/transactions/new.html.erb
<ul class="breadcrumb">
  <li><a href="<%= root_path %>"><span class="fa fa-home fa-fw"></span></a></li>
  <li><a href="<%= transactions_path %>">Transaction</a></li>
  <li><a href="<%= new_transaction_path %>">New Transaction</a></li>
  <li class="active"><strong>New</strong></li>
</ul>
<%= render 'form' %>

app/views/transactions/show.html.erb
<ul class="breadcrumb">
  <li><a href="<%= root_path %>"><span class="fa fa-home fa-fw"></span></a></li>
  <li><a href="<%= transactions_path %>">Transaction</a></li>
  <li class="active"><strong>Show</strong></li>
</ul>
<div class="container-fluid">
  <div class="row main">
    <div class="col-sm-12 page-header">
      <div class="col-lg-4">
        <h3>Transaction Details</h3>
      </div>
      <div class="col-sm-offset-6 col-sm-2">
        <button class= "btn btn-default"><%= link_to 'Edit', edit_transaction_path, class: "pull-right" %></button>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-5">
      <dl class="dl-horizontal">
        <dt><strong>User: </strong></dt> <dd><%= @transaction.try(:user).try(:firstname) %></dd>
        <dt><strong>Amount: </strong></dt> <dd><%= @transaction.trans_amount %></dd>
        <dt><strong>Transaction Type: </strong></dt> <dd><%= @transaction.trans_type %></dd>
        <dt><strong>Date: </strong></dt> <dd><%= @transaction.created_at %></dd>
      </dl>
    </div>
  </div>
</div>
<div>
  <%= link_to "Back", transactions_path, class: "btn btn-primary" %>
</div>

app/views/users/shared/_links.html.erb
<% if controller_name != 'sessions' %>
  <%= link_to t('.sign_in', default: 'Sign in'), new_session_path(resource_name) %><br />
<% end %>

<% if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t('.sign_up', default: 'Sign up'), new_registration_path(resource_name) %><br />
<% end %>

<% if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to t('.forgot_your_password', default: 'Forgot your password?'), new_password_path(resource_name) %><br />
<% end %>

<% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('.didn_t_receive_confirmation_instructions', default: "Didn't receive confirmation instructions?"), new_confirmation_path(resource_name) %><br />
<% end %>

<% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t('.didn_t_receive_unlock_instructions', default: "Didn't receive unlock instructions?"), new_unlock_path(resource_name) %><br />
<% end %>

<% if devise_mapping.omniauthable? %>
  <% resource_class.omniauth_providers.each do |provider| %>
  <%= link_to t('.sign_in_with_provider', provider: provider.to_s.titleize, default: "Sign in with #{provider.to_s.titleize}"), omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>